/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void rollArrayCheck() {
        Library classUnderTest = new Library();
        int check = 6;
        int test = classUnderTest.roll(check).length;
        assertEquals(test, check);
    }

    @Test void containsDuplicate() {
        Library classUnderTest = new Library();
        int[] trial1 = {3,4,5,6,3,2};
        int[] trial2 = {3,2,4,1,6,7,8};
        assertTrue(classUnderTest.containsDuplicate(trial1));
        assertFalse(classUnderTest.containsDuplicate(trial2));
    }

    @Test void checkAvgOfArray() {
        Library classUnderTest = new Library();
        int [] tester = {3,4,5,6,3,2};
        double ans = 3.0;
        assertEquals(classUnderTest.avgOfArray(tester), ans);
    }

    @Test void checkMinAvgOfMatrix() {
        Library classUnderTest = new Library();
        int[][] tester = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        double ans = 57.0;
        assertEquals(classUnderTest.minAvgOfMatrix(tester), ans);
    }

}
