/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void cogitoRestaurant(){
        Restaurant leCinq = new Restaurant("le Cinq", 4);
        assertNotNull(leCinq);
    }

    @Test void toStringRestaurant(){
        Restaurant leCinq = new Restaurant("le Cinq", 4);
        System.out.println(leCinq.toString());
        assertEquals("le Cinq is rated 3.0 stars and has an expense of 4", leCinq.toString());
    }

    @Test void cogitoReview(){
        Review good = new Review("Great food and atmosphere", 4, "austin");
        assertNotNull(good);
    }

    @Test void totalRatingOfRestaurant(){
        Restaurant leCinq = new Restaurant("le Cinq", 4);
        Review good = new Review("Great food and atmosphere", 5, "austin");
        Review okay = new Review("The wine could have been better", 4, "austin");
        Review bad = new Review("Too expensive", 2, "austin");
        leCinq.addReview(good);
        leCinq.addReview(okay);
        leCinq.addReview(bad);
        assertEquals((double) 11/3, leCinq.getRating());
        System.out.println(leCinq.toString());
    }

    @Test void toStringReview(){
        Review good = new Review("Great food and atmosphere", 5, "Austin");
        assertEquals("""
                User: Austin
                Review: Great food and atmosphere
                Number of stars: 5""", good.toString());
    }
}
